### ISSUE TITLE
Support try/catch

### ISSUE THREAD

**Issue by ljmatan** [ethanblake4/dart_eval#48]
Reproduction:

```
void _print() {
  try {
    print('a');
  } catch (e) {
    print('b');
  }
}
```

**Comment by ethanblake4** [comment]
Indeed, exception handling in general is not really supported yet in dart_eval. I haven't yet had a chance to write down my thoughts on this yet, so I'll put everything here that I believe needs to be done to get this to work: 

- [ ] Annotate values with runtime type sets at function & field boundaries
- [ ] Support runtime type-tests (ie. the `is` keyword)
- [ ] Catch all errors at bridge entry boundaries in the runtime
- [ ] Add a catch stack with runtime-type annotated entries, and bytecode ops to push/pop to/from the catch stack
- [ ] Add bridge bindings for Exception and StackTrace
- [ ] Add a bytecode throw op that iterates backwards through the call, scope, and catch stacks, appending scope entries to the stack trace until it a ) finds a bridge exit boundary, at which point it will actually throw or b) finds a matching catch boundary, at which point it will resume program execution there with the synthesized stack trace
- [ ] Support try/catch and throw in the compiler, including for statement flow analysis
- [ ] (later) support rethrow in the compiler
- [ ] (later) support the Never type somehow
- [ ] (later) line number annotation data for stack traces

As you can probably tell, this is kind of a massive undertaking which is why I've been putting it off. It's definitely high on my list of priorities though!

**Comment by ethanblake4** [comment]
Partial support added in v0.6.0. Leaving this open until the implementation is spec-compliant.

**Comment by ethanblake4** [comment]
Closing as this is effectively complete in v0.7.0, including `rethrow`. Still may need some minor tweaks and fixes in later versions.
